version: "3"
services:
  web:
    build: 
      context: .
      args:
        APP_PORT: 8080
        APP_HOST: "0.0.0.0"
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: user
      POSTGRES_USER: user
      POSTGRES_DB: db
    ports:
        - "5432:5432"
        